version: '3'

services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /app
        env_file:
            - ../.env.dev
        ports:
            - 8000:8000
        volumes:
            - ..:/app
        command: sleep infinity

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
        container_name: elasticsearch
        environment:
            node.name: elasticsearch
            cluster.name: es-docker-cluster
            discovery.type: single-node
            xpack.security.enabled: "false"
            http.port: 9200
        ports:
            - 9200:9200
        volumes:
            - es-data:/usr/share/elasticsearch/data

    kibana:
        image: docker.elastic.co/kibana/kibana:8.1.0
        ports:
            - 5601:5601
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
volumes:
    es-data: