version: '3'

services:
    app:
        build:
            context: ..
            dockerfile: Dockerfile
        environment:
            PYTHONPATH: /app
        env_file:
            - ../.env.stage
        ports:
            - 8000:8000
        volumes:
            - ..:/app
        command: sleep infinity