name: Deploy to Cloud Run

on:
  workflow_dispatch:

jobs:
  run-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/642808392706/locations/global/workloadIdentityPools/gift-build/providers/1
          service_account: gift-build@intern-project-433907.iam.gserviceaccount.com

      - name: Set up the Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Run Cloud Build
        run: |
          gcloud builds submit \
          --config=cloudbuild.yaml \
          --substitutions=_ELASTIC_URL=${{ secrets.ELASTIC_URL }} \
          _ELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}